INSERT INTO socio (nombre,apellidos,email) VALUES ('Pepito','Fernandez','pepito@example.com')
INSERT INTO socio (nombre, apellidos, email) VALUES ('Juan', 'Perez', 'juan@example.com')
INSERT INTO socio (nombre, apellidos, email) VALUES ('Maria', 'Lopez', 'maria@example.com')
INSERT INTO socio (nombre, apellidos, email) VALUES ('Carlos', 'Gomez', 'carlos@example.com')
INSERT INTO barco (matricula,nombre,amarre,cuota,id_socio) VALUES ('BO100','Enterprise',1,250.95,1)
INSERT INTO barco (matricula,nombre,amarre,cuota,id_socio) VALUES ('BO101','El intrepido',2,250.95,1)
INSERT INTO barco (matricula, nombre, amarre, cuota, id_socio) VALUES ('BO102', 'La Perla', 3, 300.50, 2)
INSERT INTO barco (matricula, nombre, amarre, cuota, id_socio) VALUES ('BO103', 'El Navegante', 4, 280.75, 3)
INSERT INTO barco (matricula, nombre, amarre, cuota, id_socio) VALUES ('BO104', 'Mar Azul', 5, 320.00, 1)
INSERT INTO patron (nombre,apellidos,email) VALUES ('Pepito','Fernandez','pepito@example.com')
INSERT INTO patron (nombre,apellidos,email) VALUES ('Pepito2','Fernandez','pepito2@example.com')
INSERT INTO patron (nombre, apellidos, email) VALUES ('Ana', 'Martinez', 'ana@example.com')
INSERT INTO patron (nombre, apellidos, email) VALUES ('Luis', 'Rodriguez', 'luis@example.com')
INSERT INTO patron (nombre, apellidos, email) VALUES ('Sofia', 'Garcia', 'sofia@example.com')
INSERT INTO salida (fecha_hora_salida,destino,patron_id,id_barco) VALUES ('2025-04-08 15:07:00','Valencia port',1,2)
INSERT INTO salida (fecha_hora_salida,destino,patron_id,id_barco) VALUES ('2025-04-08 17:07:00','Barcelona',2,2)
INSERT INTO salida (fecha_hora_salida, destino, patron_id, id_barco) VALUES ('2025-04-09 10:00:00', 'Lisboa', 4, 1)
INSERT INTO salida (fecha_hora_salida, destino, patron_id, id_barco) VALUES ('2025-04-09 12:00:00', 'Oporto', 5, 3)
INSERT INTO salida (fecha_hora_salida, destino, patron_id, id_barco) VALUES ('2025-04-09 14:00:00', 'Faro', 3, 2)